CREATE TABLE EXTERNAL_SUPPLIER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
    SUPPLIER_CODE VARCHAR(100) NOT NULL COMMENT '供应商唯一ID',
    SUPPLIER_NAME VARCHAR(100) NOT NULL COMMENT '供应商名称',
    FETCHER_TYPE VARCHAR(32) NOT NULL COMMENT '文件获取类型：SFTP / REST',
    REMOTE_SUB_DIR VARCHAR(512) DEFAULT NULL COMMENT 'SFTP远端子目录；REST类型无值',
    IS_ENABLE TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0禁用，1启用',
    UPDATE_FREQUENCY INT COMMENT '上传频率,单位分钟',
    FILE_NAME_RULE VARCHAR(512) COMMENT '文件命名规则',
    S3_BUCKET VARCHAR(32) COMMENT 'S3文件存储的BUCKET',
    CREATOR VARCHAR(32) COMMENT '创建人',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFIER VARCHAR(32) COMMENT '更新人',
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT UK_SUPPLIER_CODE UNIQUE (SUPPLIER_CODE),
    CONSTRAINT CK_SUPPLIER_FETCHER_TYPE CHECK (FETCHER_TYPE IN ('SFTP', 'REST')),
    CONSTRAINT CK_SUPPLIER_ENABLE CHECK (IS_ENABLE IN (0, 1)),
    CONSTRAINT CK_SUPPLIER_FREQUENCY CHECK (UPDATE_FREQUENCY IS NULL OR UPDATE_FREQUENCY >= 1)
);

CREATE TABLE DATA_TASK (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '任务唯一ID',
    SUPPLIER_CODE VARCHAR(100) NOT NULL COMMENT '供应商唯一ID',
    SOURCE_UNIQUE_KEY VARCHAR(255) NOT NULL COMMENT '源文件全局唯一去重键',
    SOURCE_FILE_NAME VARCHAR(255) NOT NULL COMMENT '源业务文件名',
    SOURCE_REMOTE_PATH VARCHAR(512) DEFAULT NULL COMMENT 'SFTP远端完整路径；REST无值',
    SOURCE_FILE_SIZE BIGINT DEFAULT NULL COMMENT '源文件字节大小',
    SOURCE_MTIME BIGINT DEFAULT NULL COMMENT '源文件修改时间戳(毫秒)',
    FETCHER_TYPE VARCHAR(32) NOT NULL COMMENT '文件获取类型：SFTP / REST',
    STATUS VARCHAR(32) NOT NULL COMMENT '任务状态',
    LOCAL_TEMP_PATH VARCHAR(512) DEFAULT NULL COMMENT '本次执行的本地临时文件路径',
    DOWNLOAD_RETRY_TIMES INT NOT NULL DEFAULT 0 COMMENT '下载累计重试次数',
    UPDATE_RETRY_TIMES INT NOT NULL DEFAULT 0 COMMENT '上传累计重试次数',
    INFORM_RETRY_TIMES INT NOT NULL DEFAULT 0 COMMENT '通知下游累计重试次数',
    S3_BUCKET VARCHAR(32) COMMENT 'S3文件存储的BUCKET',
    TARGET_S3_KEY VARCHAR(512) DEFAULT NULL COMMENT '上传成功后S3对象KEY',
    INFORM_TIME DATETIME COMMENT '通知下游时间',
    FEEDBACK_FLAG VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '下游是否反馈：Y/N',
    CREATOR VARCHAR(32) COMMENT '创建人',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFIER VARCHAR(32) COMMENT '更新人',
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    CONSTRAINT UK_SOURCE_UNIQUE_KEY UNIQUE (SOURCE_UNIQUE_KEY),
    CONSTRAINT CK_TASK_FETCHER_TYPE CHECK (FETCHER_TYPE IN ('SFTP', 'REST')),
    CONSTRAINT CK_TASK_STATUS CHECK (STATUS IN ('PENDING', 'DOWNLOADING', 'DOWNLOAD_FAILED', 'UPLOADED', 'UPLOAD_FAILED', 'INFORMED', 'INFORM_FAILED', 'COMPLETED')),
    CONSTRAINT CK_TASK_FEEDBACK CHECK (FEEDBACK_FLAG IN ('Y', 'N')),
    CONSTRAINT CK_TASK_RETRY CHECK (DOWNLOAD_RETRY_TIMES >= 0 AND UPDATE_RETRY_TIMES >= 0 AND INFORM_RETRY_TIMES >= 0)
);

CREATE INDEX IDX_SOURCE_STATUS ON DATA_TASK (STATUS, SOURCE_UNIQUE_KEY);
CREATE INDEX IDX_CREATE_TIME ON DATA_TASK (CREATE_TIME);

CREATE TABLE SYS_USER (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NULL,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SAML_NAME_ID VARCHAR(255) NULL,
    IS_ENABLE TINYINT NOT NULL DEFAULT 1,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_SYS_USER_SAML_NAME_ID UNIQUE (SAML_NAME_ID),
    CONSTRAINT CK_SYS_USER_ENABLE CHECK (IS_ENABLE IN (0, 1))
);

CREATE TABLE SYS_GROUP (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    GROUP_CODE VARCHAR(64) NOT NULL,
    GROUP_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(512) NULL,
    IS_ENABLE TINYINT NOT NULL DEFAULT 1,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UK_SYS_GROUP_CODE UNIQUE (GROUP_CODE),
    CONSTRAINT CK_SYS_GROUP_ENABLE CHECK (IS_ENABLE IN (0, 1))
);

CREATE TABLE SYS_PERMISSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PERMISSION_CODE VARCHAR(100) NOT NULL,
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    IS_ENABLE TINYINT NOT NULL DEFAULT 1,
    CONSTRAINT UK_SYS_PERMISSION_CODE UNIQUE (PERMISSION_CODE),
    CONSTRAINT CK_SYS_PERMISSION_ENABLE CHECK (IS_ENABLE IN (0, 1))
);

CREATE TABLE SYS_USER_GROUP (
    USER_ID BIGINT NOT NULL,
    GROUP_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, GROUP_ID),
    CONSTRAINT FK_SYS_USER_GROUP_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SYS_USER_GROUP_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID) ON DELETE CASCADE
);

CREATE TABLE SYS_GROUP_PERMISSION (
    GROUP_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    PRIMARY KEY (GROUP_ID, PERMISSION_ID),
    CONSTRAINT FK_SYS_GROUP_PERMISSION_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SYS_GROUP (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SYS_GROUP_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES SYS_PERMISSION (ID) ON DELETE CASCADE
);

CREATE TABLE AUDIT_LOG (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    OPERATOR VARCHAR(64) NOT NULL,
    ACTION VARCHAR(64) NOT NULL,
    TARGET_TYPE VARCHAR(50) NOT NULL,
    TARGET_ID VARCHAR(64) NULL,
    DETAIL VARCHAR(1000) NULL,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SYS_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, RESOURCE_TYPE, ACTION) VALUES
('dashboard:read', '查看仪表盘', 'dashboard', 'read'),
('supplier:read', '查看供应商', 'supplier', 'read'),
('supplier:write', '管理供应商', 'supplier', 'write'),
('task:read', '查看数据任务', 'task', 'read'),
('task:retry', '重试数据任务', 'task', 'retry'),
('user:read', '查看用户', 'user', 'read'),
('user:write', '管理用户', 'user', 'write'),
('group:read', '查看群组', 'group', 'read'),
('group:write', '管理群组', 'group', 'write'),
('permission:read', '查看权限', 'permission', 'read'),
('permission:write', '管理权限', 'permission', 'write');

INSERT INTO SYS_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES
('ADMIN', '系统管理员', '拥有全部管理端权限'),
('OPERATOR', '运营人员', '拥有业务查看、任务重试和供应商管理权限'),
('VIEWER', '只读用户', '仅拥有业务数据查看权限');

INSERT INTO SYS_GROUP_PERMISSION (GROUP_ID, PERMISSION_ID)
SELECT g.ID, p.ID
FROM SYS_GROUP g
CROSS JOIN SYS_PERMISSION p
WHERE g.GROUP_CODE = 'ADMIN';

INSERT INTO SYS_GROUP_PERMISSION (GROUP_ID, PERMISSION_ID)
SELECT g.ID, p.ID
FROM SYS_GROUP g
JOIN SYS_PERMISSION p ON p.PERMISSION_CODE IN ('dashboard:read', 'supplier:read', 'supplier:write', 'task:read', 'task:retry')
WHERE g.GROUP_CODE = 'OPERATOR';

INSERT INTO SYS_GROUP_PERMISSION (GROUP_ID, PERMISSION_ID)
SELECT g.ID, p.ID
FROM SYS_GROUP g
JOIN SYS_PERMISSION p ON p.PERMISSION_CODE IN ('dashboard:read', 'supplier:read', 'task:read')
WHERE g.GROUP_CODE = 'VIEWER';
