INSERT INTO SYS_USER (USERNAME, PASSWORD_HASH, FULL_NAME, EMAIL, SAML_NAME_ID, IS_ENABLE)
SELECT '__ADMIN_BOOTSTRAP__', NULL, '系统管理员', 'admin@external-data.local', NULL, 0
FROM SYS_GROUP
WHERE GROUP_CODE = 'ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM SYS_USER WHERE EMAIL = 'admin@external-data.local'
  );

INSERT INTO SYS_USER_GROUP (USER_ID, GROUP_ID)
SELECT u.ID, g.ID
FROM SYS_USER u
JOIN SYS_GROUP g ON g.GROUP_CODE = 'ADMIN'
WHERE u.EMAIL = 'admin@external-data.local'
  AND NOT EXISTS (
      SELECT 1
      FROM SYS_USER_GROUP ug
      WHERE ug.USER_ID = u.ID AND ug.GROUP_ID = g.ID
  );
