INSERT INTO SYS_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, RESOURCE_TYPE, ACTION)
VALUES ('audit:read', '查看审计日志', 'audit', 'read');

INSERT INTO SYS_GROUP_PERMISSION (GROUP_ID, PERMISSION_ID)
SELECT g.ID, p.ID
FROM SYS_GROUP g
JOIN SYS_PERMISSION p ON p.PERMISSION_CODE = 'audit:read'
WHERE g.GROUP_CODE = 'ADMIN';
